name: Flet Windows Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.11
  FLET_CLI_VERSION: 0.28.3
  PYTHONUTF8: 1
  FLET_CLI_NO_RICH_OUTPUT: 1
  UV_NO_PROGRESS: 1

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install flet-cli
        run: |
          python -m pip install --upgrade pip
          pip install flet-cli==${{ env.FLET_CLI_VERSION }}

      - name: Diagnose environment
        run: |
          chcp 65001
          set PYTHONIOENCODING=utf-8
          flet doctor

      - name: Build for Windows
        run: |
          chcp 65001
          set PYTHONIOENCODING=utf-8
          flet build windows --verbose --no-rich-output --build-number=${{ env.BUILD_NUMBER }} --build-version=${{ env.BUILD_VERSION }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/windows
