name: Windows Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  # Build metadata
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0

  # Versions to use
  PYTHON_VERSION: 3.13.7
  FLET_CLI_VERSION: 0.28.3

  # Environment tuning
  PYTHONUTF8: 1
  FLET_CLI_NO_RICH_OUTPUT: 1
  UV_NO_PROGRESS: 1

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install flet-cli ${{ env.FLET_CLI_VERSION }}
        run: |
          python -m pip install --upgrade pip
          pip install flet-cli==${{ env.FLET_CLI_VERSION }}

      - name: Setup Flutter 3.35.5
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.5"
          channel: "stable"

      - name: Verify Flutter installation
        run: flutter --version

      - name: Flet Build Windows
        env:
          FLET_FLUTTER_PATH: C:\hostedtoolcache\windows\flutter\stable-3.35.5-x64
        run: |
          echo "Using Flutter from: $env:FLET_FLUTTER_PATH"
          $env:FLET_FLUTTER_PATH\bin\flutter.bat --version
          flet build windows --verbose --no-rich-output --build-number=$env:BUILD_NUMBER --build-version=$env:BUILD_VERSION

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-artifact
          path: build/windows
          if-no-files-found: error
          overwrite: false
